fix: definir as variáveis coletadas pela gui no projeto principal possibilitando o seu uso no algoritmo principal.
einsteinfloripa/corretor-simulados pull request #12
Opened 2023-01-30 17:11 UTC by maecco

# Descrição
Essa PR tem como objetivo conectar o lado da gui com o algoritmo principal.

## Definição de novas variáveis.
Definição, na função principal, de variáveis provindas do usuário do programa, são elas:
- O caminho dos arquivos de gabarito
- O caminho dos arquivos de resposta
- O caminho de saída do relatório final
- O tipo de correção a ser executada

Em `src/__init__.py`:

![image](https://user-images.githubusercontent.com/92338508/215544159-ba6fc942-9af7-4aec-ac49-803b0b9221b9.png)

OBS: Por enquanto o algoritmo suporta apenas um caminho de gabarito e resposta, por isso, se mais caminhos forem coletados pela GUI apenas o primeiro será repassado para o algoritmo.

## Novos arquivos
Em `src/auxilio` foi a adicionada a pasta `path` que possui a função `get_caminho_de_saida` para auxiliar na formação do caminho final de saída.

![image](https://user-images.githubusercontent.com/92338508/215545831-3ac3600a-3095-4111-bce2-87b64277fb25.png)

2023-01-30 23:01 UTC, maecco commented on src/auxilio/path.py
> +# Cria pasta relatorio(1) se existir cria relatorio(1) ...
Cria pasta "relatorio" se existir cria "relatorio(1)", "relatorio(2)" ...

2023-01-31 16:57 UTC, maecco commented
A correção esta funcionando com os exemplos! :)

2023-02-01 16:56 UTC, vianaz reviewed
@maecco tentei executar o algoritmo e tive esse error


[Screencast from 01-02-2023 13:52:54.webm](https://user-images.githubusercontent.com/97882083/216109257-d2b70585-62d0-4d28-b64b-375a344f86f4.webm)

2023-02-01 17:05 UTC, maecco commented
Isso aconteceu porque o caminho de dados dos alunos esta "hard coded" para '.../recursos/exemplos/simuenem/dados-alunos.csv', e no seu caso o o caminho esta '.../recursos/exemplos/simuenem/simuenem_exemplos/dados-alunos.csv'.

2023-02-01 17:24 UTC, vianaz commented
@maecco Perfeito! Resolvi aqui, acredito que por enquanto podemos deixar `hard coded`, mas acho que uma coisa legal pra a gente adicionar nessa PR é um prompt avisando se foi corrigido os simulados, porque atualmente isso vem de um log no console, como segue na imagem:

![image](https://user-images.githubusercontent.com/97882083/216116946-7f08dde9-dea4-470c-93f0-ef75b4aad89e.png)

O que você acha?

2023-02-02 12:27 UTC, vianaz commented on src/__init__.py
> +    path_saida = get_caminho_de_saida(dados["caminho_de_saida"])
@maecco esse nome `path_saida` me incomoda um pouco, porque não diz muita coisa, path de saida pra o que? pra onde? talvez um nome como `path_output_arquivos_correção` (ainda acho que podemos achar algum nome melhor que esse hahaha), mas o que vou te pedir é pra ir no `Jira` e criar uma task atrelada a epic `Tech Debits` para refatorar isso no futuro! Favor quando fizer isso deixar um comentário nessa PR com o link pra task, qualquer dificuldade só me chamar!

2023-02-02 12:27 UTC, vianaz requested changes

2023-02-02 12:27 UTC, vianaz commented on src/auxilio/path.py
> +        path_saida = os.path.join(dir_selecioado, f"output_{cont}")
```suggestion
def get_caminho_de_saida(dir_selecionado):

    cont = 0
    while True:
        path_saida = os.path.join(dir_selecionado, f"output_{cont}")
```

2023-02-02 14:29 UTC, maecco commented on src/auxilio/path.py
> +        path_saida = os.path.join(dir_selecioado, f"output_{cont}")
@vianaz Feito!

2023-02-02 18:03 UTC, vianaz commented on src/__init__.py
> +    path_saida = get_caminho_de_saida(dados["caminho_de_saida"])
em conversa preferimos ajustar esse problema logo nessa como pode ser visto no commit 43f2fcc

2023-02-02 22:08 UTC, vianaz approved these changes

2023-02-02 22:09 UTC, merged