AdicionaGUI
einsteinfloripa/corretor-simulados pull request #5
Opened 2023-01-18 15:28 UTC by maecco

# Descrição
Esta PR tem como principal objetivo a adição de uma interface gráfica que facilite a utilização do programa por parte dos usuários. 

## 1. Versionamento e bibliotecas.
- A versão do Python foi atualizada para a versão 3.10
- A interface gráfica foi criada usando a biblioteca `pyside6`.
- A biblioteca `PyInquirer` foi removida.

## 2. GUI
A interface gráfica é capaz de proporcionar o usuário:
1. Selecionar um ou mais arquivos com os dados necessário para a correção das provas, garantindo que os arquivos selecionados tenham o formato correto (XLSX ou CSV).
3. Selecionar o tipo de correção que deve ser feito.
4. Escolher o nome e local para gerar o arquivo de saída.

2023-01-18 15:46 UTC, maecco commented on src/GUI/__init__.py
> +    @Slot()
Esse decorator não apresenta nenhuma função adicional para o código na pratica, e pode ser ignorado sem problemas. O pyside6 pede para que o decorator seja adicionado para evitar comportamentos indefinido.

2023-01-19 23:05 UTC, vianaz commented on src/GUI/__init__.py
> +    @Slot()
@maecco aconselho você deixar um link para aonde você leu isso, acredito que não precisa deixar um novo comentário, mas apenas editar o seu comentário anterior!

2023-01-20 19:26 UTC, maecco reviewed
Esse commit saiu com o nome errado, esqueci que já tinha adicionado o modo debug. Devo usar um comando do git para consertar?

2023-01-20 19:27 UTC, maecco reviewed
Esse commit saiu com o nome errado, esqueci que já tinha adicionado o modo debug. Devo usar um comando do git para consertar?

2023-01-25 13:13 UTC, vianaz requested changes
@maecco como a gente havia falado, quando a pessoa fosse escolher a opção `Salvar Como`, deveria ser capaz de escolher uma pasta e não um arquivo, além disso acredito que podemos mudar o nome para `Salvar na Pasta`, segue imagem de como está agora

![image](https://user-images.githubusercontent.com/97882083/214572300-0d41a508-00de-4cbb-8c33-b800e4d66267.png)

2023-01-25 13:39 UTC, vianaz requested changes

2023-01-25 13:39 UTC, vianaz commented on src/GUI/widgets/__init__.py
> +    def set_text(self, text):
@maecco mudar para portugês

2023-01-25 13:39 UTC, vianaz commented on src/GUI/widgets/__init__.py
> +class Frame_seleçao_tipo_de_correçao(QFrame):
@maecco mesmo comentário anterior

2023-01-25 13:39 UTC, vianaz commented on src/GUI/widgets/__init__.py
> +class Frame_seleçao_caminhos_de_entrada(QFrame):
@maecco preferivel que não use 'ç', pelo fato de ser um caracter especial pode gerar alguns bugs meio chatos, mas deixo isso como um alteração opcional e use `PascalCase`

2023-01-25 13:39 UTC, vianaz commented on src/GUI/widgets/__init__.py
> +class Caminho_label_btn_pair(QGroupBox):
@maecco geralmente o nome de uma classe no Python usa o `PascalCase`, modificar por favor

2023-01-25 13:39 UTC, vianaz commented on src/GUI/widgets/__init__.py
> +class Scroll_Widget_conteiner_caminhos(QScrollArea):
@maecco usar `PascalCase`

2023-01-25 14:43 UTC, maecco commented on src/GUI/__init__.py
> +        self.setFixedSize(guiCons.largura_da_janela, guiCons.altura_da_janela)
Concordo!

2023-01-25 14:46 UTC, maecco commented on src/GUI/widgets/__init__.py
> +class Frame_seleçao_caminhos_de_entrada(QFrame):
"use `PascalCase`". Vc acha melhor usar `PascalCase` no caso acima?

2023-01-25 14:55 UTC, vianaz commented on src/GUI/widgets/__init__.py
> +class Frame_seleçao_caminhos_de_entrada(QFrame):
Exato, a razão está no [comentário ](https://github.com/einsteinfloripa/corretor-simulados/pull/5#discussion_r1086651679)

2023-01-25 16:35 UTC, vianaz approved these changes

2023-01-25 16:36 UTC, merged