feat: add ps test correction and refactor interface
einsteinfloripa/corretor-simulados pull request #51
Opened 2024-03-05 02:51 UTC by maecco

## Descrição

amanha farei kk

2024-03-06 09:32 UTC, vianaz requested changes
O alinhamento ficou zuado

2024-03-06 09:32 UTC, vianaz commented on src/__main__.py
O alinhamento ali na box ficou zuado

<img width="864" alt="image" src="https://github.com/einsteinfloripa/corretor-simulados/assets/97882083/00c75f02-930b-40dc-993a-f57c19d8547a">

2024-03-06 09:32 UTC, vianaz commented on src/__main__.py
> +    #checar se os dados são válidos
```suggestion
    # Checar se os dados são válidos
```

Afim de manter o padrão, os comentários no nosso código tem um espaço e começam com letra maiuscula

2024-03-06 09:32 UTC, vianaz commented on src/__main__.py
> +    # gerar arquivo de estatisticas de correção e salvar
```suggestion
    # Gerar arquivo de estatisticas de correção e salvar
```

2024-03-06 09:32 UTC, vianaz commented on src/auxilio/checker.py
> +    #universal checks
```suggestion
    # Universal checks
```

2024-03-06 09:32 UTC, vianaz commented on src/auxilio/checker.py
> +    # valores NaN ou nulos
```suggestion
    # Valores NaN ou nulos
```

2024-03-06 09:32 UTC, vianaz commented on src/auxilio/checker.py
> +    # checa se todos os alunos em dados_alunos estão em respostas
```suggestion
    # Checa se todos os alunos em dados_alunos estão em respostas
```

2024-03-06 09:32 UTC, vianaz commented on src/auxilio/checker.py
> +    # checa se os campos obrigatórios estão presentes
```suggestion
    # Checa se os campos obrigatórios estão presentes
```

2024-03-06 09:32 UTC, vianaz commented on src/auxilio/checker.py
> +    # checa se o número de questões é o esperado
```suggestion
    # Checa se o número de questões é o esperado
```

2024-03-06 09:32 UTC, vianaz commented on src/auxilio/checker.py
> +# private
```suggestion
# Private
```

2024-03-06 09:32 UTC, vianaz commented on src/geradores/gerar_ps.py
> +    # essa operacao muda as colunas de lugar!
```suggestion
    # Essa operacao muda as colunas de lugar!
```

2024-03-06 09:32 UTC, vianaz commented on src/geradores/gerar_ps.py
> +        # mateiras = { $mateira1: { absoluto: (int), percentual: (float) }, ... }
```suggestion
    # Estatisticas das materias
    # mateiras = { $mateira1: { absoluto: (int), percentual: (float) }, ... }
```

2024-03-06 09:32 UTC, vianaz commented on src/gui/widgets/__init__.py
>          # vars
```suggestion
        # Vars
```

2024-03-06 09:32 UTC, vianaz commented on src/gui/widgets/__init__.py
>          # config
```suggestion
        # Config
```

2024-03-06 09:32 UTC, vianaz commented on src/gui/widgets/__init__.py
>          # config
```suggestion
        # Config
```

2024-03-06 09:32 UTC, vianaz commented on src/gui/widgets/__init__.py
>          # botoes
```suggestion
        # Botoes
```

2024-03-06 09:32 UTC, vianaz commented on src/gui/widgets/__init__.py
> +        # botoes
```suggestion
        # Botoes
```

2024-03-06 09:32 UTC, vianaz commented on src/leitura_e_escrita/ler_arquivo.py
> +    # checar se o caminho existe e é um diretório
```suggestion
    # Checar se o caminho existe e é um diretório
```

2024-03-06 09:32 UTC, vianaz commented on src/leitura_e_escrita/ler_arquivo.py
> +    # procurar os arquivos de dados
```suggestion
    # Procurar os arquivos de dados
```

2024-03-06 09:32 UTC, vianaz commented on src/leitura_e_escrita/ler_arquivo.py
> +    # ler e checar os arquivos
```suggestion
    # Ler e checar os arquivos
```

2024-03-06 12:23 UTC, maecco commented on src/__main__.py
Dos textos vc fala?

2024-03-06 15:49 UTC, maecco commented on src/__main__.py
Centralizado!

2024-03-07 16:41 UTC, vianaz commented on src/__main__.py
@maecco não testei mais eu confio que tu fez ksksksksk

2024-03-07 16:42 UTC, vianaz approved these changes

2024-03-07 19:25 UTC, grodrigues04 commented
Não sei se isso é erro do linux, ou do projeto. Mas quando eu clico para selecionar o diretório abre uma janela, do qual quando eu tento movimentar a posição dela no meu pc, ela movimenta a janela do corretor de provas

2024-03-07 19:36 UTC, grodrigues04 commented
Quando eu clico em corrigir com as pastas selecionas, mas sem nenhum arquivo dentro, ele cria uma pasta de output, mesmo mostrando um erro na tela. Acho que seria interessante ele não criar a pasta output, pois as condições não foram totalmente satisfeitas para o programa rodar

2024-03-07 19:38 UTC, grodrigues04 commented
Adicionar um readme de como os dados devem ser inseridos

2024-03-07 23:59 UTC, maecco commented
@grodrigues04 Certo, vou fazer isso amanha!

2024-03-12 18:37 UTC, merged